name = "cloud-omproxy-dev"
main = "src/index.ts"
compatibility_date = "2026-05-14"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "cloud_omproxy_dev"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CACHE"

[[r2_buckets]]
binding = "BACKUPS"
bucket_name = "cloud-omproxy-dev-backups"

[assets]
binding = "ASSETS"
directory = "../web/dist"
not_found_handling = "single-page-application"
run_worker_first = true
